### ISSUE TITLE
Unable to build on Ubuntu 24.04

### ISSUE THREAD

**Issue by nobody43** [roddhjav/apparmor.d#322]
Env: clean system with 'minimal' preset, on QEMU

Installation commands 1:1 from the site

Output:
```
...
Building apparmor.d profiles for ubuntu.
 ✓ Initialize a new clean apparmor.d build directory
 ✓ Ignore profiles and files from:
    ⋅ dists/ignore/main.ignore
    ⋅ dists/ignore/ubuntu.ignore
 ✓ Merge all profiles into a unified apparmor.d directory
panic: rename .build/apparmor.d/epiphany .build/apparmor.d/epiphany.apparmor.d: no such file or directory

goroutine 1 [running]:
github.com/roddhjav/apparmor.d/pkg/prebuild/cfg.Overwriter.Apt({0x60?}, {0xc0000aa000, 0x11, 0x4e2110?})
	/root/apparmor.d/pkg/prebuild/cfg/files.go:77 +0x225
github.com/roddhjav/apparmor.d/pkg/prebuild/prepare.Configure.Apply({{{0x5a8b49, 0x1e}, {0x5a2b63, 0x9}, {0x0, 0x0}}})
	/root/apparmor.d/pkg/prebuild/prepare/configure.go:36 +0xdc
github.com/roddhjav/apparmor.d/pkg/prebuild.Prepare()
	/root/apparmor.d/pkg/prebuild/prebuild.go:58 +0x70
main.aaPrebuild()
	/root/apparmor.d/cmd/prebuild/main.go:74 +0x195
main.main()
	/root/apparmor.d/cmd/prebuild/main.go:93 +0x9a
make[1]: *** [Makefile:15: all] Error 2
make[1]: Leaving directory '/root/apparmor.d'
dh_auto_build: error: make -j2 "INSTALL=install --strip-program=true" returned exit code 2
make: *** [debian/rules:7: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```

Not urgent, just letting know.

**Comment by roddhjav** [comment]
My bad, I forgot to add the epiphany profile. This should work now. When Github Action will support Ubuntu 24.04, this issue will be automatically detected.

**Comment by nobody43** [comment]
Thanks.
Do you have a planned date for ditching 22.04 support?

**Comment by roddhjav** [comment]
Support for 22.04 won't be removed. While Debian is while behind Ubuntu 22.04 it does not require any work to keep Ubuntu 22.04.

Meanwhile, Ubuntu 24.04 is currently the only distribution supporting apparmor 4, they will be a bit of work to do once arch & opensuse update.
